### ISSUE TITLE
The theory of the function update()

### ISSUE THREAD

**Issue by xiaoyang-git** [jkac/ogre-openvr#1]
Hello, I am very excited to see your code, but I don't understand why you set camera's orientation and pose like this, please tell me, thank you!
    // ----------------------------------------------------------------
    //  renders the frame
    // ----------------------------------------------------------------
    void update()
    {
        // update the parent camera node's orientation and position with the new tracking data
        g_orientation = g_poseNeutralOrientation.Inverse() \* g_mat4HMDPose.extractQuaternion();
        g_cameraNode->setOrientation(g_orientation);

```
    g_position = g_mat4HMDPose.getTrans();
    g_cameraNode->setPosition(g_position - g_poseNeutralPosition);
```

**Comment by jkac** [comment]
g_poseNeutralOrientation and g_poseNeutralPosition aren't used yet so that can be simplified to:

```
g_orientation = g_mat4HMDPose.extractQuaternion();
g_cameraNode->setOrientation(g_orientation);

g_position = g_mat4HMDPose.getTrans();
g_cameraNode->setPosition(g_position);
```

neutral position & orientation will be the offset which allow "re-centering" of the HMD

**Comment by xiaoyang-git** [comment]
Thank you very much, I have a camera designed by myself in my program, it has own position and orientation, should I do this follow process:
`Ogre::Quaternion qTransform = g_mat4HMDPose.extractQuaternion();`
`Ogre::Quaternion qNewOrientation = g_cameraNode->getOrientation()*qTransform;`
`g_cameraNode->setOrientation(qNewOrientation );`

//For left eye render
`g_positionHMD = g_mat4HMDPose.getTrans();
 g_positionHMDEye = g_mat4eyePosLeft.getTrans();
g_cameraNode->setPosition(g_cameraNode->getPosition+g_positionHMD+g_positionHMDEye  );
`

//For right eye render
`g_positionHMD = g_mat4HMDPose.getTrans();
 g_positionHMDEye = g_mat4eyePosRight.getTrans();
g_cameraNode->setPosition(g_cameraNode->getPosition+g_positionHMD+g_positionHMDEye  );`

**Comment by jkac** [comment]
I'm not sure about your program - I only know about mine =)

g_cameras[0] and g_cameras[1] are the cameras but their transform & orientation doesn't change -- it's just relative to g_cameraNode. g_cameraNode is what moves.

If you have another camera and it moves with the HMD, then I'd probably create that in initOgreCameras() and attach it to g_cameraNode -- then it will automatically move with the rest of them.

**Comment by xiaoyang-git** [comment]
I know what are you mean, maybe that I have problems with my expression, I am very sorry. I am trying to render the scenes which are rendered in my program on the platform OGRE, I have create a camera in OGRE, it has own position and orientation, so what should I do? Now I have already rendered out the scenes, but when I move and roll the helmet, the scenes are always not true. I really want to finish this, thank you so much.

**Comment by jkac** [comment]
I was thinking about it differently -- sorry it took me so long.  Right now you probably have a camera and you control it with keyboard & mouse.  But this creates its own cameras and those are controlled by HMD sensor input only.  And you need to combine the two.  Correct? 

Your scene hierarchy might be something like:
`root scene node --> player node (keyboard & mouse input) --> your camera (no input)`
(In other words, your camera doesn't move independently from the body)

You'll want something like:
`root scene node --> player node (keyboard & mouse input) --> VR cameras (HMD sensor input)`

So you still control your player node with whatever controls you like -- and in addition to that the VR cameras are moving independently and relative to your character based on sensor input.

Does that make sense?  You won't create your own camera unless you need to do something more complicated.

I'll have an update soon with a few fixes-- and a few extra getter functions for attaching the parent HMD node where ever in your hierarchy you like.  Also renaming g_cameraNode to g_HMDNode so it's less confusing.

**Comment by xiaoyang-git** [comment]
Thank you very much! I have already finished that work, just do that : GetCurrentViewProjectionMatrix() multiplicative to my camera's view matrix, and it works now.
there is also some transformation neeed to do because the rendered scenes in my HMD are reverse, so make a rotate matrix to turn the rendered texture right.
